### ISSUE TITLE
SIEGSEGV

### ISSUE THREAD

**Issue by pdrabik223** [mateuszkojro/video_player#10]
https://github.com/mateuszkojro/video_player/blob/407bbd91fffae693d5200d5bd04e7f0fdeed2f6c/GLWidget.h#L51-L52
gdy używam new_pipeline i kompiluję  używając debbugera tutaj dostaję SIEGSEGV, 
tylko że w tym miejscu wczytujemy statyczne zdjęcie

**Comment by mateuszkojro** [comment]
Fixed in:
https://github.com/mateuszkojro/video_player/commit/b4f338307b6e39acb0e25757307958b6b1f52d63
but I believe it still des not work
